name: Update Nebraska Football Schedule

on:
  schedule:
    - cron: '0 8-17 * * *'  # Runs every hour from 8 AM to 5 PM CST
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure correct Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run the Python script
        run: python nebraska_schedule.py

      # Ensure file timestamp is updated
      - name: Touch the index.html to update the timestamp
        run: touch index.html

      # Commit the updated HTML file
      - name: Commit the updated HTML file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-update index.html via GitHub Actions" || echo "No changes to commit"

      # Push changes using the personal access token (PAT)
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}  # Make sure you create this secret in your repo
        run: |
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
